### ISSUE TITLE
[FEATURE] Add tech demo & compliance disclaimers

### ISSUE THREAD

**Issue by chainum** [harmony-one/swoop-testing#14]
We need to add disclaimers explaining that the project is a tech demo and that users use it at their own risk.

We also need to add a compliance disclaimer explaining that US residents are prohibited from using the exchange.

This is what Niteesh asked us to add:

Disclaimers
- This project is a tech demo in beta. Use at your own risk.
- Swoop prohibits using its services if you are located, incorporated or otherwise established in, or a citizen or resident of the United States or prohibited jurisdictions.

Can you take a look at this @hypnagonia?

**Comment by hypnagonia** [comment]
done

**Comment by chainum** [comment]
I updated the styling a bit and corrected the initial message that gets displayed.

We also need to link to a larger statement somewhere as well. We could e.g. do this using a modal:

![Screenshot 2020-10-26 at 17 07 38](https://user-images.githubusercontent.com/13743/97200706-daa79c80-17b1-11eb-88ab-e7033ef091bc.png)

Text:
Disclaimer note: This project is a tech demo in beta. You understand and expressly accept that the beta version of SWOOP is provided to you at your own risk on an “AS IS” and “UNDER DEVELOPMENT” basis. THE DEVELOPERS OF SWOOP MAKE NO WARRANTY WHATSOEVER WITH RESPECT TO THE BETA DEMO, INCLUDING ANY (A) WARRANTY OF MERCHANTABILITY; (B) WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE; (C) WARRANTY OF TITLE; OR (D) WARRANTY AGAINST INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OF A THIRD PARTY; WHETHER ARISING BY LAW, COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE OF TRADE, OR OTHERWISE. Swoop prohibits using its services if you are located, incorporated or otherwise established in, or a citizen or resident of the United States or prohibited jurisdictions.

**Comment by lijiang2087** [comment]
use this final

Disclaimer note:
This project is a tech demo in beta. You understand and expressly accept that the beta version of SWOOP is provided to you at your own risk on an “AS IS” and “UNDER DEVELOPMENT” basis. THE DEVELOPERS OF SWOOP MAKE NO WARRANTY WHATSOEVER WITH RESPECT TO THE BETA DEMO, INCLUDING ANY (A) WARRANTY OF MERCHANTABILITY; (B) WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE; (C) WARRANTY OF TITLE; OR (D) WARRANTY AGAINST INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OF A THIRD PARTY; WHETHER ARISING BY LAW, COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE OF TRADE, OR OTHERWISE.
Nationals and residents of the following countries are restricted from participation: Afghanistan, Cuba, Democratic Republic of the Congo, Guinea-Bissau, Iran, Iraq, Lebanon, Libya, Myanmar, North Korea, Somalia, Sudan, Syria, Yemen, Zimbabwe, and the Crimea region of Ukraine.
The project is operated by Pangaea Community around the globe and Hemenglian Technology outside the United States.

**Comment by hypnagonia** [comment]
updated

**Comment by chainum** [comment]
Looks good, just fixed the formatting a little bit:
<img width="1677" alt="Screenshot 2020-10-27 at 17 54 04" src="https://user-images.githubusercontent.com/13743/97335355-0ee88f00-187e-11eb-9ea8-a22ae74d60be.png">
